name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2

      - name: Download Dependencies
        run: go mod tidy

      - name: Test
        run: |
          make test
          bash -c '/bin/bash <(curl -s https://codecov.io/bash)'

      - name: Build
        run: go build -v .
  license-check:
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
    - uses: actions/checkout@v2
    - name: Download License Utility
      run: go get -u github.com/google/addlicense
    - name: Check License Headers
      run: |
        shopt -s globstar
        addlicense -check **/*.go
      shell: bash
